- hosts: localhost
  become: true
  tasks:
  - name: Install CRAN R  packages locally
    command: | 
       Rscript --slave --no-save --no-restore-history -e
       "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) {
               install.packages(pkgs='{{ item }}',
               repos=c('http://stat.ethz.ch/CRAN'));
               print('Added'); } else { print('Already installed'); }"
    register: r_result
    failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
    changed_when: "'Added' in r_result.stdout"
    with_items:
       - tstools
       - tsbox
       - curl
       - kofdata
       - rmarkdown
       - blogdown
       - flexdashboard
       - tstools
       - dygraphs
       - devtools
       - readtext
       - quanteda
       - textcat
       - data.table
       - dplyr
       - jsonlite
       - ggplot2
       - reprex
