- hosts: localhost
  become: true
  tasks:
  - name: Install OS level tools
    apt:
     pkg:
      - curl
      - libcurl4-openssl-dev
      - texinfo
      - xorg-dev
      - whois
      - ca-certificates
      - gnupg-agent
      - xclip
      - libssl-dev
      - libxml2-dev
      - libpoppler-cpp-dev
      - software-properties-common
    tags: os
  - name: Engines and interpreters
    apt:
     pkg:       
      - nodejs-dev
      - node-gyp
      - npm
    tags: 
      - engines
  - name: node packages
    command: npm install -g @quasar/cli
    tags: node
  - name: latex packages
    apt: 
     pkg:
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra 
